[workspace]
members = [
    "legacy-algebra",
    "fast-poly",
    "brainfuck",
    "stark",
    "fri",
    "optimized-fields",
    "mini-stark"
]

[profile.release]
debug = true
codegen-units = 1
lto = true