[package]
name = "fri"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-crypto-primitives = "0.3.0"
ark-ff = { git = "https://github.com/arkworks-rs/algebra" }
# ark-ff-optimized = { path = "../optimized-fileds" }
num-traits = "0.2.14"
ark-poly = { git = "https://github.com/arkworks-rs/algebra" }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra" }

[patch.crates-io]
ark-ff = { git = "https://github.com/arkworks-rs/algebra" }
ark-poly = { git = "https://github.com/arkworks-rs/algebra" }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra" }
# ark-ff-optimized = { path = "../optimized-fileds" }