[package]
name = "algebra"
version = "0.1.0"
edition = "2021"

[profile.test]
opt-level = 2

[dependencies]
num-traits = "0.2.14"
serde = { version = "1.0", features = ["derive"] }
num-bigint = { version = "0.4", default-features = false }
rand = "0.8.5"

[dev-dependencies]
rand_pcg = "0.3.1"