[package]
name = "brainfuck"
version = "0.1.0"
edition = "2021"

[dependencies]
legacy-algebra = { path = "../legacy-algebra" }
num-bigint = { version = "0.4", default-features = false }
rand = "0.8.5"
num-traits = "0.2.14"
ark-ff = { git = "https://github.com/arkworks-rs/algebra", branch = "explicit-derive-feature" }

[dev-dependencies]
ark-ff-optimized = { git = "https://github.com/andrewmilson/optimized-fields" }

[patch.crates-io]
ark-ff = { git = "https://github.com/arkworks-rs/algebra", branch = "explicit-derive-feature" }
ark-ff-optimized = { git = "https://github.com/andrewmilson/optimized-fields" }
