[package]
name = "mini-stark"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.6"
digest = "0.10.5"
rand_chacha = "0.3.1"
ark-std = { git = "https://github.com/arkworks-rs/std" }
ark-ff = { git = "https://github.com/arkworks-rs/algebra" }
ark-poly = { git = "https://github.com/arkworks-rs/algebra" }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra" }
ark-ff-optimized = { git = "https://github.com/andrewmilson/optimized-fields" }
fast-poly = { path = "../fast-poly" }
anyhow = "1.0.65"
thiserror = "1.0.37"
rayon = { version = "1.5.3", optional = true }

[features]
default = []
asm = [ "sha2/asm" ]
parallel = [ "dep:rayon", "ark-std/parallel", "fast-poly/parallel" ]

[patch.crates-io]
ark-std = { git = "https://github.com/arkworks-rs/std" }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra" }
ark-poly = { git = "https://github.com/arkworks-rs/algebra" }
ark-ff = { git = "https://github.com/arkworks-rs/algebra" }