[package]
name = "mini-stark"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.6"
digest = "0.10.5"
rand_chacha = "0.3.1"
ark-ff = { git = "https://github.com/arkworks-rs/algebra" }
ark-poly = { git = "https://github.com/arkworks-rs/algebra" }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra" }
ark-ff-optimized = { path = "../optimized-fields" }
fast-poly = { path = "../fast-poly" }

[patch.crates-io]
ark-serialize = { git = "https://github.com/arkworks-rs/algebra" }
ark-poly = { git = "https://github.com/arkworks-rs/algebra" }
ark-ff = { git = "https://github.com/arkworks-rs/algebra" }